"""Initial Migration
Intentionally empty because this migration only sets up our starting state
for alembic.

Revision ID: b3f88596952c
Revises: 
Create Date: 2023-03-27 16:35:05.368005

"""
import sqlalchemy as sa
import sqlmodel
from alembic import op

# revision identifiers, used by Alembic.
revision = "b3f88596952c"
down_revision = None
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
